# Generated by Django 4.0.6 on 2024-11-05 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='photo',
        ),
        migrations.AddField(
            model_name='service',
            name='customized_options',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='experiences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='renovation_plans',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='feedback',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
