# Generated by Django 5.0.9 on 2024-11-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_credit_card_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='covid_vaccination_status',
            field=models.CharField(choices=[('vaccinated', 'Vaccinated'), ('not_vaccinated', 'Not Vaccinated')], default='not_vaccinated', max_length=20),
        ),
    ]
