# Generated by Django 5.0.9 on 2024-11-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_covid_vaccination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a single photo for your service', null=True, upload_to='service_photos/'),
        ),
    ]
